### ISSUE TITLE
this.selectedControl is undefined

### ISSUE THREAD

**Issue by mmatyas** [Dr-Ocelot/tetralegends#11]
So I was just trying to change the hard drop key to the Up arrow, but then the game started spamming JS errors:

![Screenshot_2020-08-16_17-16-49](https://user-images.githubusercontent.com/4354863/90337747-d6f2df00-dfe4-11ea-8688-a77d58f81151.png)

**Comment by mmatyas** [comment]
PS. Leaving and entering the config menu seems to fix it.

**Comment by JJCUBER** [comment]
Leaving and entering the config menu doesn't fix it in my case and it occurs whenever you hover over quite a few of the bindings.  Unfortunately, it seems like this project isn't really actively being worked on or maintained anymore.

**Comment by vanillyn** [comment]
Could someone try to replicate this issue then prove the console/log?

**Comment by doktorocelot** [comment]
this issue had actually been fixed a while back

**Comment by vanillyn** [comment]
OH i misread the comment
