### ISSUE TITLE
Tetra Legends Plus..?

### ISSUE THREAD

**Issue by vanillyn** [Dr-Ocelot/tetralegends#13]
I've researched Tetra Legends, and there is a continuation/successor, however there is no working link. If this project is abandoned, where would it go? (I've created a fork of it)

![image](https://user-images.githubusercontent.com/108785622/212394647-72a268eb-8ee9-4fc2-a345-2a12aa4e4f6c.png)
(Tetra Legends Plus site now)

**Comment by doktorocelot** [comment]
plus was an unofficial mod developed by other people
as far as i know, that project is gone/dead, but i wouldnt know much about it

**be warned when forking this project:**
i wrote this years ago before i learned about a lot of programming theory and design — as such, the codebase is very much a tangled mess as i was oblivious to the advanced concepts of object oriented programming, functional programming and test-driven development
you're free to play around with it, but i would personally recommend against anything beyond toying with the project as there are anti-patterns and design issues everywhere that require so much work to solve, you're better off creating a project from scratch

**Comment by vanillyn** [comment]
oh, alright
i cant get into contact with the other person so ill assume its dead

and thats alright! i love tinkering with it and i dont mind scuffed code
dont really know how i can improve on it though outside of bugfixes
