### ISSUE TITLE
What happened to the hosted copy? tetralegends.app seems to not have an IP address.

### ISSUE THREAD

**Issue by TheoCGaming** [Dr-Ocelot/tetralegends#15]

**Comment by doktorocelot** [comment]
I had recently transferred the domain name to a new company. It looks like there's still issues, so I'll try to sort it as soon as I can.

**Comment by doktorocelot** [comment]
Github is refusing to give me a certificate, and .app domains require a certificate. I'm going to disconnect the domain for a couple of days and try again later in the week. I'm sorry for the inconvenience.

**Comment by doktorocelot** [comment]
finally fixed this nonsense
please allow some time for it to propagate if you dont see it yet
